<?php

return [
    ['name' => 'Afghanistan', 'code' => 'AF', 'aliases' => ['AFG']],
    ['name' => 'Albania', 'code' => 'AL', 'aliases' => ['ALB']],
    ['name' => 'Algeria', 'code' => 'DZ', 'aliases' => ['ALG', 'DZ']],
    ['name' => 'Andorra', 'code' => 'AD', 'aliases' => []],
    ['name' => 'Angola', 'code' => 'AO', 'aliases' => []],
    ['name' => 'Argentina', 'code' => 'AR', 'aliases' => ['ARG']],
    ['name' => 'Armenia', 'code' => 'AM', 'aliases' => []],
    ['name' => 'Australia', 'code' => 'AU', 'aliases' => ['AUS']],
    ['name' => 'Austria', 'code' => 'AT', 'aliases' => []],
    ['name' => 'Azerbaijan', 'code' => 'AZ', 'aliases' => []],

    ['name' => 'Bahamas', 'code' => 'BS', 'aliases' => []],
    ['name' => 'Bahrain', 'code' => 'BH', 'aliases' => []],
    ['name' => 'Bangladesh', 'code' => 'BD', 'aliases' => []],
    ['name' => 'Belarus', 'code' => 'BY', 'aliases' => ['Belorussia']],
    ['name' => 'Belgium', 'code' => 'BE', 'aliases' => []],
    ['name' => 'Belize', 'code' => 'BZ', 'aliases' => []],
    ['name' => 'Benin', 'code' => 'BJ', 'aliases' => []],
    ['name' => 'Bhutan', 'code' => 'BT', 'aliases' => []],
    ['name' => 'Bolivia', 'code' => 'BO', 'aliases' => []],
    ['name' => 'Bosnia and Herzegovina', 'code' => 'BA', 'aliases' => ['BiH']],
    ['name' => 'Botswana', 'code' => 'BW', 'aliases' => []],
    ['name' => 'Brazil', 'code' => 'BR', 'aliases' => ['BRA']],
    ['name' => 'Bulgaria', 'code' => 'BG', 'aliases' => []],
    ['name' => 'Burkina Faso', 'code' => 'BF', 'aliases' => []],
    ['name' => 'Cambodia', 'code' => 'KH', 'aliases' => []],
    ['name' => 'Cameroon', 'code' => 'CM', 'aliases' => []],
    ['name' => 'Canada', 'code' => 'CA', 'aliases' => ['CAN']],
    ['name' => 'Chile', 'code' => 'CL', 'aliases' => []],
    ['name' => 'China', 'code' => 'CN', 'aliases' => ['Mainland China', 'CN']],
    ['name' => 'Colombia', 'code' => 'CO', 'aliases' => []],
    ['name' => 'Costa Rica', 'code' => 'CR', 'aliases' => []],
    ['name' => 'Croatia', 'code' => 'HR', 'aliases' => []],
    ['name' => 'Cuba', 'code' => 'CU', 'aliases' => []],
    ['name' => 'Cyprus', 'code' => 'CY', 'aliases' => []],
    ['name' => 'Czech Republic', 'code' => 'CZ', 'aliases' => ['Czechia']],

    ['name' => 'Denmark', 'code' => 'DK', 'aliases' => []],
    ['name' => 'Dominican Republic', 'code' => 'DO', 'aliases' => ['DR']],

    ['name' => 'Ecuador', 'code' => 'EC', 'aliases' => []],
    ['name' => 'Egypt', 'code' => 'EG', 'aliases' => ['EGY']],
    ['name' => 'El Salvador', 'code' => 'SV', 'aliases' => []],
    ['name' => 'Estonia', 'code' => 'EE', 'aliases' => []],
    ['name' => 'Ethiopia', 'code' => 'ET', 'aliases' => []],

    ['name' => 'Finland', 'code' => 'FI', 'aliases' => []],
    ['name' => 'France', 'code' => 'FR', 'aliases' => ['FRA']],

    ['name' => 'Georgia', 'code' => 'GE', 'aliases' => []],
    ['name' => 'Germany', 'code' => 'DE', 'aliases' => ['DEU']],
    ['name' => 'Ghana', 'code' => 'GH', 'aliases' => []],
    ['name' => 'Greece', 'code' => 'GR', 'aliases' => []],
    ['name' => 'Guatemala', 'code' => 'GT', 'aliases' => []],

    ['name' => 'Haiti', 'code' => 'HT', 'aliases' => []],
    ['name' => 'Honduras', 'code' => 'HN', 'aliases' => []],
    ['name' => 'Hong Kong', 'code' => 'HK', 'aliases' => ['HK SAR', 'Hong-Kong']],
    ['name' => 'Hungary', 'code' => 'HU', 'aliases' => []],

    ['name' => 'Iceland', 'code' => 'IS', 'aliases' => []],
    ['name' => 'India', 'code' => 'IN', 'aliases' => ['IND']],
    ['name' => 'Indonesia', 'code' => 'ID', 'aliases' => []],
    ['name' => 'Iran', 'code' => 'IR', 'aliases' => []],
    ['name' => 'Iraq', 'code' => 'IQ', 'aliases' => []],
    ['name' => 'Ireland', 'code' => 'IE', 'aliases' => []],
    ['name' => 'Israel', 'code' => 'IL', 'aliases' => []],
    ['name' => 'Italy', 'code' => 'IT', 'aliases' => ['ITA']],

    ['name' => 'Jamaica', 'code' => 'JM', 'aliases' => []],
    ['name' => 'Japan', 'code' => 'JP', 'aliases' => ['JPN']],
    ['name' => 'Jordan', 'code' => 'JO', 'aliases' => []],

    ['name' => 'Kazakhstan', 'code' => 'KZ', 'aliases' => []],
    ['name' => 'Kenya', 'code' => 'KE', 'aliases' => []],
    ['name' => 'Kuwait', 'code' => 'KW', 'aliases' => []],
    ['name' => 'Kyrgyzstan', 'code' => 'KG', 'aliases' => []],

    ['name' => 'Laos', 'code' => 'LA', 'aliases' => []],
    ['name' => 'Latvia', 'code' => 'LV', 'aliases' => []],
    ['name' => 'Lebanon', 'code' => 'LB', 'aliases' => []],
    ['name' => 'Libya', 'code' => 'LY', 'aliases' => []],
    ['name' => 'Lithuania', 'code' => 'LT', 'aliases' => []],
    ['name' => 'Luxembourg', 'code' => 'LU', 'aliases' => []],

    ['name' => 'Madagascar', 'code' => 'MG', 'aliases' => []],
    ['name' => 'Malaysia', 'code' => 'MY', 'aliases' => []],
    ['name' => 'Maldives', 'code' => 'MV', 'aliases' => []],
    ['name' => 'Mali', 'code' => 'ML', 'aliases' => []],
    ['name' => 'Malta', 'code' => 'MT', 'aliases' => []],
    ['name' => 'Mexico', 'code' => 'MX', 'aliases' => ['MEX']],
    ['name' => 'Moldova', 'code' => 'MD', 'aliases' => []],
    ['name' => 'Mongolia', 'code' => 'MN', 'aliases' => []],
    ['name' => 'Montenegro', 'code' => 'ME', 'aliases' => []],
    ['name' => 'Morocco', 'code' => 'MA', 'aliases' => []],
    ['name' => 'Mozambique', 'code' => 'MZ', 'aliases' => []],

    ['name' => 'Nepal', 'code' => 'NP', 'aliases' => []],
    ['name' => 'Netherlands', 'code' => 'NL', 'aliases' => ['Holland']],
    ['name' => 'New Zealand', 'code' => 'NZ', 'aliases' => []],
    ['name' => 'Nicaragua', 'code' => 'NI', 'aliases' => []],
    ['name' => 'Nigeria', 'code' => 'NG', 'aliases' => []],
    ['name' => 'North Macedonia', 'code' => 'MK', 'aliases' => ['Macedonia']],
    ['name' => 'Norway', 'code' => 'NO', 'aliases' => []],

    ['name' => 'Oman', 'code' => 'OM', 'aliases' => []],

    ['name' => 'Pakistan', 'code' => 'PK', 'aliases' => []],
    ['name' => 'Panama', 'code' => 'PA', 'aliases' => []],
    ['name' => 'Paraguay', 'code' => 'PY', 'aliases' => []],
    ['name' => 'Peru', 'code' => 'PE', 'aliases' => []],
    ['name' => 'Philippines', 'code' => 'PH', 'aliases' => ['PHL']],
    ['name' => 'Poland', 'code' => 'PL', 'aliases' => []],
    ['name' => 'Portugal', 'code' => 'PT', 'aliases' => []],

    ['name' => 'Qatar', 'code' => 'QA', 'aliases' => []],

    ['name' => 'Romania', 'code' => 'RO', 'aliases' => []],
    ['name' => 'Russia', 'code' => 'RU', 'aliases' => ['Russian Federation']],
    ['name' => 'Rwanda', 'code' => 'RW', 'aliases' => []],

    ['name' => 'Saudi Arabia', 'code' => 'SA', 'aliases' => ['KSA']],
    ['name' => 'Senegal', 'code' => 'SN', 'aliases' => []],
    ['name' => 'Serbia', 'code' => 'RS', 'aliases' => []],
    ['name' => 'Singapore', 'code' => 'SG', 'aliases' => ['SGP']],
    ['name' => 'Slovakia', 'code' => 'SK', 'aliases' => []],
    ['name' => 'Slovenia', 'code' => 'SI', 'aliases' => []],
    ['name' => 'Somalia', 'code' => 'SO', 'aliases' => []],
    ['name' => 'South Africa', 'code' => 'ZA', 'aliases' => ['RSA']],
    ['name' => 'South Korea', 'code' => 'KR', 'aliases' => ['Korea', 'Republic of Korea']],
    ['name' => 'Spain', 'code' => 'ES', 'aliases' => []],
    ['name' => 'Sri Lanka', 'code' => 'LK', 'aliases' => []],
    ['name' => 'Sweden', 'code' => 'SE', 'aliases' => []],
    ['name' => 'Switzerland', 'code' => 'CH', 'aliases' => []],

    ['name' => 'Taiwan', 'code' => 'TW', 'aliases' => ['Taiwan, Province of China']],
    ['name' => 'Tajikistan', 'code' => 'TJ', 'aliases' => []],
    ['name' => 'Tanzania', 'code' => 'TZ', 'aliases' => []],
    ['name' => 'Thailand', 'code' => 'TH', 'aliases' => []],
    ['name' => 'Tunisia', 'code' => 'TN', 'aliases' => []],
    ['name' => 'Turkey', 'code' => 'TR', 'aliases' => ['Türkiye']],
    ['name' => 'Turkmenistan', 'code' => 'TM', 'aliases' => []],

    ['name' => 'Uganda', 'code' => 'UG', 'aliases' => []],
    ['name' => 'Ukraine', 'code' => 'UA', 'aliases' => []],
    ['name' => 'United Arab Emirates', 'code' => 'AE', 'aliases' => ['UAE']],
    ['name' => 'United Kingdom', 'code' => 'GB', 'aliases' => ['UK', 'Great Britain']],
    ['name' => 'United States', 'code' => 'US', 'aliases' => ['USA', 'United States of America']],
    ['name' => 'Uruguay', 'code' => 'UY', 'aliases' => []],
    ['name' => 'Uzbekistan', 'code' => 'UZ', 'aliases' => []],

    ['name' => 'Venezuela', 'code' => 'VE', 'aliases' => []],
    ['name' => 'Vietnam', 'code' => 'VN', 'aliases' => []],

    ['name' => 'Yemen', 'code' => 'YE', 'aliases' => []],

    ['name' => 'Zambia', 'code' => 'ZM', 'aliases' => []],
    ['name' => 'Zimbabwe', 'code' => 'ZW', 'aliases' => []],
];
